# For the code flow with Keycloak we also need to create the code_verifier and code_challenge
# Documentation here: https://www.rfc-editor.org/rfc/rfc7636#section-4

# We can do it using the code_challenge_method "plain" or "S256"
# Depending on which method is used,
# plain -> code_challenge = code_verifier
# S256 -> code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))
# You can use an online tool to generate the code_verifier and code_challenge -> https://developer.pingidentity.com/en/tools/pkce-code-generator.html

// @name 1. Start the code flow
// @no-redirect

< {%
    S256Verifier = "lvtWiVdbDYGmrIGAx43ycnVWPwE2I8JWbRR16UGRGI9pInKIlVQy64qzirS8AzGKvqdhDw0sPZo6OK8ku7EbfATI9QCwqnE6Mzc8DTcU7A";
    plainVerifier = "ZfZx5x-P6qkUeJof_UDFD_cVKMiQhhDHGVeq6_A8SwE";

    codeChallengeMethod = "S256";
    codeVerifier = "S256" === codeChallengeMethod ? S256Verifier : plainVerifier;
    client.global.set("codeVerifier", codeVerifier);
    client.log("codeChallengeMethod is: " + codeChallengeMethod);
    client.log("codeVerifier is: " + codeVerifier);
    request.variables.set("code_challenge_method", codeChallengeMethod);
%}

GET {{auth0BaseUrl}}/authorize
    ?response_type=code
    &client_id={{auth0ClientId}}
    &redirect_uri=http://localhost:9090/login/oauth2/code/auth0
    &scope={{auth0Scopes}}
    &state={{state}}
    &audience={{audience}}
    &code_challenge={{code_challenge}}
    &code_challenge_method={{code_challenge_method}}

> {%
    loginUrl = response.headers.valueOf("Location");
    client.log('loginUrl is: ' + loginUrl);
    loginUrl = "https://product-management-backend.eu.auth0.com" + loginUrl
    client.log('loginUrl is: ' + loginUrl);
    client.global.set("loginUrl", loginUrl);
%}

###

// @name 2. User login
// @no-redirect
POST {{loginUrl}}
Content-Type: application/x-www-form-urlencoded

username={{auth0Username}}&password={{auth0UserPassword}}

> {%
    redirect = response.headers.valueOf("Location");
    redirect = "https://product-management-backend.eu.auth0.com" + redirect
    client.log('redirect is: ' + redirect);
    client.global.set("redirect", redirect);
%}

###

// @name 3. Auth0 has an additional step in which we need to do a GET on the /authorize/resume endpoint
// @no-redirect
GET {{redirect}}

> {%
    redirect = response.headers.valueOf("Location");
    client.log('redirect is: ' + redirect);
    client.global.set("redirect", redirect);

    code = redirect.match('code=(.*)&state')[1];
    client.log('code: ' + code);
    client.global.set("code", code);
%}

###

// @name 4. Request the access token
// @no-redirect
POST https://product-management-backend.eu.auth0.com/oauth/token
Content-Type: application/x-www-form-urlencoded

code_verifier={{codeVerifier}}&client_id={{auth0ClientId}}&client_secret={{auth0ClientSecret}}&grant_type=authorization_code&code={{code}}&state={{state}}&redirect_uri=http://localhost:9090/login/oauth2/code/auth0

> {%
    const accessToken = response.body.access_token;
    client.log('accessToken is: ' + accessToken);
    client.global.set("accessToken", accessToken);

    //
    const idToken = response.body.id_token;
    client.log('idToken is: ' + idToken);
    client.global.set("idToken", idToken);
%}

###

// @name 5. Get the user info
GET https://product-management-backend.eu.auth0.com/userinfo
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}