POST http://localhost:{{authServerPort}}/oauth/token?grant_type={{password_type_client_grant_type}}&username={{username}}&password={{password}}&scope={{password_type_client_scope}}
Authorization: Basic {{password_type_client_id}} {{password_type_client_password}}

> {%
const accessToken = response.body.access_token;
client.log('accessToken is: ' +  accessToken);
client.global.set("accessToken", accessToken);
 %}