# First obtain a token using the code flow with one of the auth servers
# -> auth0_get_jwt_code_flow.http
# -> keycloack_get_jwt_code_flow.http
# -> spring_auth_server_get_jwt_code_flow.http

GET {{resourceServerBaseUrl}}/hello
Authorization: Bearer {{accessToken}}